### PR TITLE
Update running-hrea-backend.md

### PR DESCRIPTION
**Pull request by tommycp3**
Updated the "hc sandbox call install-app-bundle" to "hc sandbox call install-app" because "install-app-bundle" is not in "hc sandbox call --help" menu

### CODE REVIEW

**Comment by Connoropolous** [comment]
thanks. Did you try it and this worked?

**Comment by tommycp3** [comment]
I just tried to use install another .happ file and I get the same error.

It seems install-app-bundle doesn't exist anymore and the cli wants to correct to install-app 

Install-app doesn't seem to do anything and not getting any genesis changes in my sandbox directory. So I'm puzzled and stuck, but happy to turn it into an issue and keep testing if that helps?

**Comment by Connoropolous** [comment]
@tommycp3 so what versions are we talking about? (of `hc` and `hrea`)

**Comment by tommycp3** [comment]
holochain_cli 0.1.3
and 
hrea happ-0.1.0-beta

However I just tried happ-0.1.3-beta and it installed successfully only using install-app



So "hc sandbox call install-app" I guess, is now the correct command.

**Comment by Connoropolous** [comment]
K great!

**Pull request merged**
